default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: umigame_app
  password: password
  timeout: 5000
  
development:
  <<: *default
  database: umigame_app_development

test:
  <<: *default
  database: umigame_app_test

production:
  <<: *default